# Generated by Django 3.1.7 on 2022-01-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
